name = "mono-api"
[[workloads]]
name = "api"
kind = "deployment"
  [[workloads.containers]]
  name = "app"
  is_primary = true
  image_ref = "docker.io/calliopeai/astrolift-sample-api:main-df5ffa3"
  port = 8080
    [workloads.containers.healthcheck]
    kind = "http"
    value = "/health"
    port = 8080
